      MODULE RESPONSE_SPECTRA_STUF

      USE PENTIUM_II_KIND, ONLY : LONG, DOUBLE
      USE PARAMS, ONLY          : RSTYPE

      IMPLICIT NONE

      INTEGER(LONG), PARAMETER :: MAX_RS_FREQ    = 20000
      INTEGER(LONG), PARAMETER :: MAX_RS_TAB     = 20000
      INTEGER(LONG), PARAMETER :: MAX_RS_DIR     = 16
      INTEGER(LONG), PARAMETER :: MAX_RS_MAP     = 512
      INTEGER(LONG), PARAMETER :: MAX_RS_SPECSEL = 256
      INTEGER(LONG), PARAMETER :: MAX_RS_TABLES  = 512
      INTEGER(LONG), PARAMETER :: MAX_RS_TABDMP1 = 2048

      INTEGER(LONG) :: RS_FREQ1_SID  = 0
      INTEGER(LONG) :: RS_DLOAD_SID  = 0
      INTEGER(LONG) :: RS_RLOAD1_SID = 0
      INTEGER(LONG) :: RS_RLOAD1_EXCITE_SID = 0
      INTEGER(LONG) :: RS_TABLED1_ID = 0

      INTEGER(LONG) :: RS_NUM_FREQ = 0
      INTEGER(LONG) :: RS_NUM_TAB  = 0
      INTEGER(LONG) :: RS_NUM_DIR  = 0
      INTEGER(LONG) :: RS_NUM_RLOAD1 = 0
      INTEGER(LONG) :: RS_NUM_DLOAD_TERM = 0
      INTEGER(LONG) :: RS_NUM_SPECSEL = 0
      INTEGER(LONG) :: RS_NUM_TABLES = 0
      INTEGER(LONG) :: RS_NUM_SUPORT = 0
      INTEGER(LONG) :: RS_NUM_TABDMP1 = 0

      INTEGER(LONG) :: RS_DIR_SID(MAX_RS_DIR) = 0
      INTEGER(LONG) :: RS_DIR_EXCITE_SID(MAX_RS_DIR) = 0
      INTEGER(LONG) :: RS_DIR_TABLED1_ID(MAX_RS_DIR) = 0
      INTEGER(LONG) :: RS_TABLE_IDS(MAX_RS_TABLES) = 0
      INTEGER(LONG) :: RS_TABLE_BEG(MAX_RS_TABLES) = 0
      INTEGER(LONG) :: RS_TABLE_END(MAX_RS_TABLES) = 0
      INTEGER(LONG) :: RS_RLOAD1_SID_LIST(MAX_RS_MAP) = 0
      INTEGER(LONG) :: RS_RLOAD1_EXCITE_LIST(MAX_RS_MAP) = 0
      INTEGER(LONG) :: RS_RLOAD1_TABLED1_LIST(MAX_RS_MAP) = 0
      INTEGER(LONG) :: RS_DLOAD_SID_LIST(MAX_RS_MAP) = 0
      INTEGER(LONG) :: RS_DLOAD_RLOAD1_LIST(MAX_RS_MAP) = 0
      REAL(DOUBLE)  :: RS_DLOAD_SCALE_LIST(MAX_RS_MAP) = 1.0D0
      INTEGER(LONG) :: RS_SUPORT_GRID(MAX_RS_MAP) = 0
      INTEGER(LONG) :: RS_SUPORT_COMP(MAX_RS_MAP) = 0
      INTEGER(LONG) :: RS_SDAMP_SID = 0
      INTEGER(LONG) :: RS_TABDMP1_SID_LIST(MAX_RS_TABDMP1) = 0
      REAL(DOUBLE)  :: RS_TABDMP1_FREQ_LIST(MAX_RS_TABDMP1) = 0.0D0

      INTEGER(LONG) :: RS_SPECSEL_LINE(MAX_RS_SPECSEL) = 0
      CHARACTER(1)  :: RS_SPECSEL_KIND(MAX_RS_SPECSEL) = ' '
      INTEGER(LONG) :: RS_SPECSEL_TABLED1(MAX_RS_SPECSEL) = 0
      REAL(DOUBLE)  :: RS_SPECSEL_DAMP(MAX_RS_SPECSEL) = 0.0D0
      REAL(DOUBLE)  :: RS_SUPORT_COMP_SCALE(6) = 0.0D0
      REAL(DOUBLE)  :: RS_TABDMP1_DAMP_LIST(MAX_RS_TABDMP1) = 0.0D0

      REAL(DOUBLE) :: RS_FREQS(MAX_RS_FREQ)   = 0.0D0
      REAL(DOUBLE) :: RS_TAB_FREQ(MAX_RS_TAB) = 0.0D0
      REAL(DOUBLE) :: RS_TAB_AMP(MAX_RS_TAB)  = 0.0D0

      CONTAINS

      INTEGER(LONG) FUNCTION RS_FIND_TABLE_SLOT ( TABLED1_ID )

      INTEGER(LONG), INTENT(IN) :: TABLED1_ID
      INTEGER(LONG)             :: I

      RS_FIND_TABLE_SLOT = 0
      IF (TABLED1_ID <= 0) RETURN

      DO I=1,RS_NUM_TABLES
         IF (RS_TABLE_IDS(I) == TABLED1_ID) THEN
            RS_FIND_TABLE_SLOT = I
            RETURN
         ENDIF
      ENDDO

      END FUNCTION RS_FIND_TABLE_SLOT

      INTEGER(LONG) FUNCTION RS_GET_OR_CREATE_TABLE_SLOT ( TABLED1_ID )

      INTEGER(LONG), INTENT(IN) :: TABLED1_ID

      RS_GET_OR_CREATE_TABLE_SLOT = RS_FIND_TABLE_SLOT(TABLED1_ID)
      IF (RS_GET_OR_CREATE_TABLE_SLOT > 0) RETURN

      IF ((TABLED1_ID <= 0) .OR. (RS_NUM_TABLES >= MAX_RS_TABLES)) THEN
         RS_GET_OR_CREATE_TABLE_SLOT = 0
         RETURN
      ENDIF

      RS_NUM_TABLES = RS_NUM_TABLES + 1
      RS_GET_OR_CREATE_TABLE_SLOT = RS_NUM_TABLES
      RS_TABLE_IDS(RS_GET_OR_CREATE_TABLE_SLOT) = TABLED1_ID
      RS_TABLE_BEG(RS_GET_OR_CREATE_TABLE_SLOT) = 0
      RS_TABLE_END(RS_GET_OR_CREATE_TABLE_SLOT) = 0

      END FUNCTION RS_GET_OR_CREATE_TABLE_SLOT

      SUBROUTINE RS_SET_RLOAD1 ( RLOAD1_SID, EXCITE_SID, TABLED1_ID )

      INTEGER(LONG), INTENT(IN) :: RLOAD1_SID, EXCITE_SID, TABLED1_ID
      INTEGER(LONG)             :: I, IDX

      RS_RLOAD1_SID        = RLOAD1_SID
      RS_RLOAD1_EXCITE_SID = EXCITE_SID

      IDX = 0
      DO I=1,RS_NUM_RLOAD1
         IF (RS_RLOAD1_SID_LIST(I) == RLOAD1_SID) THEN
            IDX = I
            EXIT
         ENDIF
      ENDDO
      IF (IDX == 0) THEN
         IF (RS_NUM_RLOAD1 < MAX_RS_MAP) THEN
            RS_NUM_RLOAD1 = RS_NUM_RLOAD1 + 1
            IDX = RS_NUM_RLOAD1
         ELSE
            IDX = MAX_RS_MAP
         ENDIF
      ENDIF
      RS_RLOAD1_SID_LIST(IDX) = RLOAD1_SID
      RS_RLOAD1_EXCITE_LIST(IDX) = EXCITE_SID
      RS_RLOAD1_TABLED1_LIST(IDX) = TABLED1_ID

      IDX = 0
      DO I=1,RS_NUM_DIR
         IF ((RS_DIR_SID(I) == EXCITE_SID) .OR. (RS_DIR_EXCITE_SID(I) == EXCITE_SID)) THEN
            IDX = I
            EXIT
         ENDIF
      ENDDO

      IF (IDX == 0) THEN
         IF (RS_NUM_DIR < MAX_RS_DIR) THEN
            RS_NUM_DIR = RS_NUM_DIR + 1
            IDX = RS_NUM_DIR
            RS_DIR_SID(IDX) = EXCITE_SID
         ELSE
            IDX = MAX_RS_DIR
         ENDIF
      ENDIF

      RS_DIR_EXCITE_SID(IDX) = EXCITE_SID
      RS_DIR_TABLED1_ID(IDX) = TABLED1_ID

      END SUBROUTINE RS_SET_RLOAD1

      SUBROUTINE RS_ADD_DLOAD_TERM ( DLOAD_SID, RLOAD1_SID, SCALE )

      INTEGER(LONG), INTENT(IN) :: DLOAD_SID, RLOAD1_SID
      REAL(DOUBLE),  INTENT(IN) :: SCALE
      INTEGER(LONG)             :: I

      IF ((DLOAD_SID <= 0) .OR. (RLOAD1_SID <= 0)) RETURN

      DO I=1,RS_NUM_DLOAD_TERM
         IF ((RS_DLOAD_SID_LIST(I) == DLOAD_SID) .AND. (RS_DLOAD_RLOAD1_LIST(I) == RLOAD1_SID)) THEN
            RS_DLOAD_SCALE_LIST(I) = SCALE
            RETURN
         ENDIF
      ENDDO

      IF (RS_NUM_DLOAD_TERM < MAX_RS_MAP) THEN
         RS_NUM_DLOAD_TERM = RS_NUM_DLOAD_TERM + 1
         RS_DLOAD_SID_LIST(RS_NUM_DLOAD_TERM) = DLOAD_SID
         RS_DLOAD_RLOAD1_LIST(RS_NUM_DLOAD_TERM) = RLOAD1_SID
         RS_DLOAD_SCALE_LIST(RS_NUM_DLOAD_TERM) = SCALE
      ENDIF

      END SUBROUTINE RS_ADD_DLOAD_TERM

      REAL(DOUBLE) FUNCTION RS_GET_DLOAD_SCALE_BY_TABLE ( DLOAD_SID, TABLED1_ID )

      INTEGER(LONG), INTENT(IN) :: DLOAD_SID, TABLED1_ID
      INTEGER(LONG)             :: I, J

      RS_GET_DLOAD_SCALE_BY_TABLE = 1.0D0
      IF ((DLOAD_SID <= 0) .OR. (TABLED1_ID <= 0)) RETURN

      DO I=1,RS_NUM_DLOAD_TERM
         IF (RS_DLOAD_SID_LIST(I) /= DLOAD_SID) CYCLE
         DO J=1,RS_NUM_RLOAD1
            IF (RS_RLOAD1_SID_LIST(J) /= RS_DLOAD_RLOAD1_LIST(I)) CYCLE
            IF (RS_RLOAD1_TABLED1_LIST(J) == TABLED1_ID) THEN
               RS_GET_DLOAD_SCALE_BY_TABLE = RS_DLOAD_SCALE_LIST(I)
               RETURN
            ENDIF
         ENDDO
         DO J=1,RS_NUM_SPECSEL
            IF (RS_SPECSEL_LINE(J) /= RS_DLOAD_RLOAD1_LIST(I)) CYCLE
            IF (RS_SPECSEL_TABLED1(J) == TABLED1_ID) THEN
               RS_GET_DLOAD_SCALE_BY_TABLE = RS_DLOAD_SCALE_LIST(I)
               RETURN
            ENDIF
         ENDDO
      ENDDO

      END FUNCTION RS_GET_DLOAD_SCALE_BY_TABLE

      SUBROUTINE RS_SET_TABLED1_ID ( TABLED1_ID )

      INTEGER(LONG), INTENT(IN) :: TABLED1_ID
      INTEGER(LONG)             :: I

      RS_TABLED1_ID = TABLED1_ID
      DO I=1,RS_NUM_DIR
         IF ((RS_DIR_TABLED1_ID(I) == 0) .AND. (RS_DIR_SID(I) > 0)) THEN
            RS_DIR_TABLED1_ID(I) = TABLED1_ID
         ENDIF
      ENDDO

      END SUBROUTINE RS_SET_TABLED1_ID

      SUBROUTINE RS_ADD_TABLED1_POINT ( TABLED1_ID, XVAL, YVAL )

      INTEGER(LONG), INTENT(IN) :: TABLED1_ID
      REAL(DOUBLE),  INTENT(IN) :: XVAL, YVAL
      INTEGER(LONG)             :: SLOT

      IF (RS_NUM_TAB >= MAX_RS_TAB) RETURN

      SLOT = RS_GET_OR_CREATE_TABLE_SLOT(TABLED1_ID)
      IF (SLOT <= 0) RETURN

      RS_NUM_TAB = RS_NUM_TAB + 1
      RS_TAB_FREQ(RS_NUM_TAB) = XVAL
      RS_TAB_AMP (RS_NUM_TAB) = YVAL

      IF (RS_TABLE_BEG(SLOT) == 0) RS_TABLE_BEG(SLOT) = RS_NUM_TAB
      RS_TABLE_END(SLOT) = RS_NUM_TAB

      END SUBROUTINE RS_ADD_TABLED1_POINT

      SUBROUTINE RS_ADD_SPECSEL_PAIR ( LINE_ID, KIND, TABLED1_ID, DAMP )

      INTEGER(LONG), INTENT(IN) :: LINE_ID, TABLED1_ID
      CHARACTER(*),  INTENT(IN) :: KIND
      REAL(DOUBLE),  INTENT(IN) :: DAMP

      IF ((TABLED1_ID <= 0) .OR. (RS_NUM_SPECSEL >= MAX_RS_SPECSEL)) RETURN

      RS_NUM_SPECSEL = RS_NUM_SPECSEL + 1
      RS_SPECSEL_LINE(RS_NUM_SPECSEL)    = LINE_ID
      RS_SPECSEL_KIND(RS_NUM_SPECSEL)    = KIND(1:1)
      RS_SPECSEL_TABLED1(RS_NUM_SPECSEL) = TABLED1_ID
      RS_SPECSEL_DAMP(RS_NUM_SPECSEL)    = DAMP

      END SUBROUTINE RS_ADD_SPECSEL_PAIR

      SUBROUTINE RS_SET_SDAMP_SID ( SID )

      INTEGER(LONG), INTENT(IN) :: SID

      IF (SID > 0) RS_SDAMP_SID = SID

      END SUBROUTINE RS_SET_SDAMP_SID

      SUBROUTINE RS_SET_TABDMP1_DAMP ( SID, FREQ, DAMP )

      INTEGER(LONG), INTENT(IN) :: SID
      REAL(DOUBLE),  INTENT(IN) :: FREQ, DAMP

      IF ((SID <= 0) .OR. (DAMP < 0.0D0)) RETURN
      IF (RS_NUM_TABDMP1 >= MAX_RS_TABDMP1) RETURN

      RS_NUM_TABDMP1 = RS_NUM_TABDMP1 + 1
      RS_TABDMP1_SID_LIST (RS_NUM_TABDMP1) = SID
      RS_TABDMP1_FREQ_LIST(RS_NUM_TABDMP1) = FREQ
      RS_TABDMP1_DAMP_LIST(RS_NUM_TABDMP1) = DAMP

      END SUBROUTINE RS_SET_TABDMP1_DAMP

      REAL(DOUBLE) FUNCTION RS_GET_TABDMP1_DAMP ( SID )

      INTEGER(LONG), INTENT(IN) :: SID
      INTEGER(LONG)             :: I

      RS_GET_TABDMP1_DAMP = -1.0D0
      IF (SID <= 0) RETURN

      DO I=1,RS_NUM_TABDMP1
         IF (RS_TABDMP1_SID_LIST(I) == SID) THEN
            RS_GET_TABDMP1_DAMP = RS_TABDMP1_DAMP_LIST(I)
            RETURN
         ENDIF
      ENDDO

      END FUNCTION RS_GET_TABDMP1_DAMP

      REAL(DOUBLE) FUNCTION RS_GET_TABDMP1_DAMP_AT_FREQ ( SID, FREQ )

      INTEGER(LONG), INTENT(IN) :: SID
      REAL(DOUBLE),  INTENT(IN) :: FREQ

      INTEGER(LONG)             :: I
      INTEGER(LONG)             :: ILOW, IHIGH
      REAL(DOUBLE)              :: FREQ_LOW, FREQ_HIGH, WT

      RS_GET_TABDMP1_DAMP_AT_FREQ = -1.0D0
      IF ((SID <= 0) .OR. (RS_NUM_TABDMP1 <= 0)) RETURN

      ILOW = 0
      IHIGH = 0
      FREQ_LOW = -1.0D0
      FREQ_HIGH = -1.0D0

      DO I=1,RS_NUM_TABDMP1
         IF (RS_TABDMP1_SID_LIST(I) /= SID) CYCLE
         IF (DABS(RS_TABDMP1_FREQ_LIST(I) - FREQ) <= 1.0D-12) THEN
            RS_GET_TABDMP1_DAMP_AT_FREQ = RS_TABDMP1_DAMP_LIST(I)
            RETURN
         ENDIF
         IF (RS_TABDMP1_FREQ_LIST(I) <= FREQ) THEN
            IF ((ILOW == 0) .OR. (RS_TABDMP1_FREQ_LIST(I) > FREQ_LOW)) THEN
               ILOW = I
               FREQ_LOW = RS_TABDMP1_FREQ_LIST(I)
            ENDIF
         ENDIF
         IF (RS_TABDMP1_FREQ_LIST(I) >= FREQ) THEN
            IF ((IHIGH == 0) .OR. (RS_TABDMP1_FREQ_LIST(I) < FREQ_HIGH) .OR. (FREQ_HIGH < 0.0D0)) THEN
               IHIGH = I
               FREQ_HIGH = RS_TABDMP1_FREQ_LIST(I)
            ENDIF
         ENDIF
      ENDDO

      IF ((ILOW > 0) .AND. (IHIGH > 0)) THEN
         IF ((ILOW == IHIGH) .OR. (DABS(FREQ_HIGH - FREQ_LOW) <= 1.0D-12)) THEN
            RS_GET_TABDMP1_DAMP_AT_FREQ = RS_TABDMP1_DAMP_LIST(ILOW)
         ELSE
            WT = (FREQ - FREQ_LOW)/(FREQ_HIGH - FREQ_LOW)
            RS_GET_TABDMP1_DAMP_AT_FREQ = (1.0D0 - WT)*RS_TABDMP1_DAMP_LIST(ILOW) + WT*RS_TABDMP1_DAMP_LIST(IHIGH)
         ENDIF
      ELSE IF (ILOW > 0) THEN
         RS_GET_TABDMP1_DAMP_AT_FREQ = RS_TABDMP1_DAMP_LIST(ILOW)
      ELSE IF (IHIGH > 0) THEN
         RS_GET_TABDMP1_DAMP_AT_FREQ = RS_TABDMP1_DAMP_LIST(IHIGH)
      ENDIF

      END FUNCTION RS_GET_TABDMP1_DAMP_AT_FREQ

      SUBROUTINE RS_ACCUM_SUPORT ( GRID_ID, COMP_CODE )

      INTEGER(LONG), INTENT(IN) :: GRID_ID
      INTEGER(LONG), INTENT(IN) :: COMP_CODE
      INTEGER(LONG)             :: I, DIGIT, WORK
      LOGICAL                   :: HAVE_GRID

      HAVE_GRID = .FALSE.
      IF (GRID_ID > 0) THEN
         DO I=1,RS_NUM_SUPORT
            IF ((RS_SUPORT_GRID(I) == GRID_ID) .AND. (RS_SUPORT_COMP(I) == COMP_CODE)) THEN
               HAVE_GRID = .TRUE.
               EXIT
            ENDIF
         ENDDO
         IF ((.NOT.HAVE_GRID) .AND. (RS_NUM_SUPORT < MAX_RS_MAP)) THEN
            RS_NUM_SUPORT = RS_NUM_SUPORT + 1
            RS_SUPORT_GRID(RS_NUM_SUPORT) = GRID_ID
            RS_SUPORT_COMP(RS_NUM_SUPORT) = COMP_CODE
         ENDIF
      ENDIF

      WORK = COMP_CODE
      IF (WORK <= 0) RETURN
      DO
         DIGIT = MOD(WORK,10_LONG)
         WORK  = WORK/10_LONG
         IF ((DIGIT >= 1) .AND. (DIGIT <= 6)) THEN
            RS_SUPORT_COMP_SCALE(DIGIT) = RS_SUPORT_COMP_SCALE(DIGIT) + 1.0D0
         ENDIF
         IF (WORK <= 0) EXIT
      ENDDO

      END SUBROUTINE RS_ACCUM_SUPORT

      SUBROUTINE RS_GET_PRIMARY_SUPORT_DOF ( GRID_ID, COMP )

      INTEGER(LONG), INTENT(OUT) :: GRID_ID
      INTEGER(LONG), INTENT(OUT) :: COMP
      INTEGER(LONG)              :: DIGIT, I, WORK

      GRID_ID = 0
      COMP    = 0

      DO I=1,RS_NUM_SUPORT
         IF (RS_SUPORT_GRID(I) <= 0) CYCLE
         WORK = RS_SUPORT_COMP(I)
         DO
            DIGIT = MOD(WORK,10_LONG)
            WORK  = WORK/10_LONG
            IF ((DIGIT >= 1) .AND. (DIGIT <= 3)) THEN
               GRID_ID = RS_SUPORT_GRID(I)
               COMP    = DIGIT
               RETURN
            ENDIF
            IF (WORK <= 0) EXIT
         ENDDO
      ENDDO

      DO I=1,RS_NUM_SUPORT
         IF (RS_SUPORT_GRID(I) <= 0) CYCLE
         WORK = RS_SUPORT_COMP(I)
         DO
            DIGIT = MOD(WORK,10_LONG)
            WORK  = WORK/10_LONG
            IF ((DIGIT >= 4) .AND. (DIGIT <= 6)) THEN
               GRID_ID = RS_SUPORT_GRID(I)
               COMP    = DIGIT
               RETURN
            ENDIF
            IF (WORK <= 0) EXIT
         ENDDO
      ENDDO

      END SUBROUTINE RS_GET_PRIMARY_SUPORT_DOF

      INTEGER(LONG) FUNCTION RS_PRIMARY_SUPORT_COMP ()

      INTEGER(LONG) :: I

      RS_PRIMARY_SUPORT_COMP = 0
      DO I=1,3
         IF (RS_SUPORT_COMP_SCALE(I) > 0.0D0) THEN
            RS_PRIMARY_SUPORT_COMP = I
            RETURN
         ENDIF
      ENDDO

      DO I=4,6
         IF (RS_SUPORT_COMP_SCALE(I) > 0.0D0) THEN
            RS_PRIMARY_SUPORT_COMP = I
            RETURN
         ENDIF
      ENDDO

      END FUNCTION RS_PRIMARY_SUPORT_COMP

      REAL(DOUBLE) FUNCTION RS_INTERP_AMP ( FREQ_HZ, GACC, TABLED1_ID )

      REAL(DOUBLE), INTENT(IN) :: FREQ_HZ
      REAL(DOUBLE), INTENT(IN) :: GACC
      INTEGER(LONG), OPTIONAL, INTENT(IN) :: TABLED1_ID
      INTEGER(LONG)            :: I, IBEG, IEND, SLOT, TABLE_ID_USE
      REAL(DOUBLE)             :: XVAL, AMP_RAW

      RS_INTERP_AMP = 0.0D0
      IF (RS_NUM_TAB <= 0) RETURN
      TABLE_ID_USE = RS_TABLED1_ID
      IF (PRESENT(TABLED1_ID)) TABLE_ID_USE = TABLED1_ID

      SLOT = RS_FIND_TABLE_SLOT(TABLE_ID_USE)
      IF (SLOT > 0) THEN
         IBEG = RS_TABLE_BEG(SLOT)
         IEND = RS_TABLE_END(SLOT)
      ELSE
         IBEG = 1
         IEND = RS_NUM_TAB
      ENDIF

      IF ((IBEG <= 0) .OR. (IEND <= 0) .OR. (IEND < IBEG)) RETURN

      IF (IBEG == IEND) THEN
         AMP_RAW = RS_TAB_AMP(IBEG)
         GO TO 100
      ENDIF

      IF (RSTYPE(1:3) == 'PER') THEN
         XVAL = 1.0D0/MAX(FREQ_HZ,1.0D-12)
      ELSE
         XVAL = FREQ_HZ
      ENDIF

      IF (XVAL <= RS_TAB_FREQ(IBEG)) THEN
         AMP_RAW = RS_TAB_AMP(IBEG)
         GO TO 100
      ENDIF
      IF (XVAL >= RS_TAB_FREQ(IEND)) THEN
         AMP_RAW = RS_TAB_AMP(IEND)
         GO TO 100
      ENDIF

      AMP_RAW = RS_TAB_AMP(IBEG)
      DO I=IBEG,IEND-1
         IF ((XVAL >= RS_TAB_FREQ(I)) .AND. (XVAL <= RS_TAB_FREQ(I+1))) THEN
            IF (RS_TAB_FREQ(I+1) > RS_TAB_FREQ(I)) THEN
               AMP_RAW = RS_TAB_AMP(I) + (RS_TAB_AMP(I+1)-RS_TAB_AMP(I))*(XVAL - RS_TAB_FREQ(I)) / &
                         (RS_TAB_FREQ(I+1)-RS_TAB_FREQ(I))
            ELSE
               AMP_RAW = RS_TAB_AMP(I)
            ENDIF
            GO TO 100
         ENDIF
      ENDDO

 100  CONTINUE
      IF (RSTYPE(4:4) == 'G') THEN
         RS_INTERP_AMP = AMP_RAW*GACC
      ELSE
         RS_INTERP_AMP = AMP_RAW
      ENDIF

      END FUNCTION RS_INTERP_AMP

      END MODULE RESPONSE_SPECTRA_STUF
