      MODULE SUBR_BEGEND_LEVELS

      USE PENTIUM_II_KIND, ONLY       :  LONG

      IMPLICIT NONE

      INTEGER(LONG), PARAMETER :: LOADB_BEGEND                   = 1
      INTEGER(LONG), PARAMETER :: LOADB0_BEGEND                  = 1
      INTEGER(LONG), PARAMETER :: PRESSURE_DATA_PROC_BEGEND      = 1
      INTEGER(LONG), PARAMETER :: BAR1_BEGEND                    = 1
      INTEGER(LONG), PARAMETER :: ELMGM1_BEGEND                  = 1
      INTEGER(LONG), PARAMETER :: ELMDAT_BEGEND                  = 1
      INTEGER(LONG), PARAMETER :: CALC_ELEM_STRESSES_BEGEND      = 1
      INTEGER(LONG), PARAMETER :: CALC_ELEM_STRAINS_BEGEND       = 1
      INTEGER(LONG), PARAMETER :: CALC_ELEM_NODE_FORCES_BEGEND   = 1
      INTEGER(LONG), PARAMETER :: WRITE_FEMAP_STRE_VECS_BEGEND   = 1
      INTEGER(LONG), PARAMETER :: WRITE_FEMAP_ELFO_VECS_BEGEND   = 1

      END MODULE SUBR_BEGEND_LEVELS
