      MODULE BD_CPYRA0_Interface

      INTERFACE

      SUBROUTINE BD_CPYRA0 ( CARD, LARGE_FLD_INP, DELTA_LEDAT )

      USE PENTIUM_II_KIND, ONLY       :  LONG

      CHARACTER(LEN=*), INTENT(INOUT) :: CARD
      CHARACTER(LEN=*), INTENT(IN)    :: LARGE_FLD_INP
      INTEGER(LONG), INTENT(OUT)      :: DELTA_LEDAT

      END SUBROUTINE BD_CPYRA0

      END INTERFACE

      END MODULE BD_CPYRA0_Interface
