      SUBROUTINE BUILD_KGGD_FROM_UG

      USE PENTIUM_II_KIND, ONLY       :  BYTE, LONG
      USE IOUNT1, ONLY                :  SC1
      USE SCONTR, ONLY                :  BLNK_SUB_NAM, LTERM_KGGD
      USE PARAMS, ONLY                :  ESP0_PAUSE
      USE SPARSE_MATRICES, ONLY       :  I_KGGD, J_KGGD, KGGD
      USE STF_ARRAYS, ONLY            :  STFKEY, STF3
      USE MODEL_STUF, ONLY            :  AGRID

      USE BUILD_KGGD_FROM_UG_USE_IFs
      USE LINK_MESSAGE_Interface

      IMPLICIT NONE

      CHARACTER(LEN=LEN(BLNK_SUB_NAM)):: SUBR_NAME = 'BUILD_KGGD_FROM_UG'

      CHARACTER, PARAMETER            :: CR13 = CHAR(13)
      CHARACTER( 1*BYTE)              :: RESPONSE

      INTEGER(LONG)                   :: LTERM
      LOGICAL                         :: WE_ALLOCD_SINGLE_ELEM_ARRS

      IF (ALLOCATED(KGGD) .OR. ALLOCATED(I_KGGD) .OR. ALLOCATED(J_KGGD)) THEN
         CALL DEALLOCATE_SPARSE_MAT ( 'KGGD' )
      ENDIF

      IF (ALLOCATED(STFKEY)) CALL DEALLOCATE_STF_ARRAYS ( 'STFKEY' )
      IF (ALLOCATED(STF3  )) CALL DEALLOCATE_STF_ARRAYS ( 'STF3'   )

      CALL ESP0
      CALL LINK_MESSAGE('CALCULATE ESTIMATE OF KGGD MATRIX SIZE        ')
      LTERM = LTERM_KGGD

      IF (ESP0_PAUSE == 'Y') THEN
         WRITE(SC1,'(A,A,A,I12)') ' From ESP0: ', 'LTERM_KGGD', ' = ', LTERM
         WRITE(SC1,'(A,A)') ' Do you want to change ', 'LTERM_KGGD estimate? (Y/N)'
         READ(*,*) RESPONSE
         IF ((RESPONSE == 'Y') .OR. (RESPONSE == 'y')) THEN
            WRITE(SC1,'(A)') 'Enter new LTERM_KGGD'
            WRITE(SC1,*)
            READ(*,*) LTERM
            LTERM_KGGD = LTERM
            WRITE(SC1,'(A,I12)') 'New LTERM_KGGD will be = ', LTERM
         ENDIF
      ENDIF

      WE_ALLOCD_SINGLE_ELEM_ARRS = .FALSE.
      IF (.NOT. ALLOCATED(AGRID)) THEN
         CALL ALLOCATE_MODEL_STUF ( 'SINGLE ELEMENT ARRAYS', SUBR_NAME )
         WE_ALLOCD_SINGLE_ELEM_ARRS = .TRUE.
      ENDIF

      CALL LINK_MESSAGE('ALLOCATE MEM FOR STFKEY, STFCOL, STFPNT, STF')
      CALL ALLOCATE_STF_ARRAYS ( 'STFKEY', SUBR_NAME )
      CALL ALLOCATE_STF_ARRAYS ( 'STF3',   SUBR_NAME )

      CALL LINK_MESSAGE('G-SET STIFFNESS MATRIX PROCESSOR            ')
      CALL ESP

      CALL LINK_MESSAGE('SPARSE KGGD PROCESSOR                       ')
      CALL SPARSE_KGGD

      CALL DEALLOCATE_STF_ARRAYS ( 'STFKEY' )
      CALL DEALLOCATE_STF_ARRAYS ( 'STF3'   )

      IF (WE_ALLOCD_SINGLE_ELEM_ARRS) THEN
         CALL DEALLOCATE_MODEL_STUF ( 'SINGLE ELEMENT ARRAYS' )
      ENDIF

      WRITE(SC1,*) CR13

      END SUBROUTINE BUILD_KGGD_FROM_UG
