      SUBROUTINE CC_SDAMP ( CARD )

      USE PENTIUM_II_KIND, ONLY       :  LONG
      USE RESPONSE_SPECTRA_STUF, ONLY :  RS_SET_SDAMP_SID
      USE GET_SETID_Interface

      IMPLICIT NONE

      CHARACTER(LEN=*), INTENT(IN) :: CARD
      INTEGER(LONG)                :: SETID

      CALL GET_SETID ( CARD, SETID )
      CALL RS_SET_SDAMP_SID ( SETID )

      END SUBROUTINE CC_SDAMP
