      MODULE BD_CPYRA_Interface

      INTERFACE

      SUBROUTINE BD_CPYRA ( CARD, LARGE_FLD_INP, NUM_GRD )

      USE PENTIUM_II_KIND, ONLY       :  LONG

      CHARACTER(LEN=*), INTENT(INOUT) :: CARD
      CHARACTER(LEN=*), INTENT(IN)    :: LARGE_FLD_INP
      INTEGER(LONG), INTENT(OUT)      :: NUM_GRD

      END SUBROUTINE BD_CPYRA

      END INTERFACE

      END MODULE BD_CPYRA_Interface
