   MODULE BD_DLOAD_Interface

   INTERFACE

      SUBROUTINE BD_DLOAD ( CARD )
      CHARACTER(LEN=*), INTENT(IN) :: CARD
      END SUBROUTINE BD_DLOAD

   END INTERFACE

   END MODULE BD_DLOAD_Interface
