   MODULE BD_FREQ1_Interface

   INTERFACE

      SUBROUTINE BD_FREQ1 ( CARD )
      CHARACTER(LEN=*), INTENT(IN) :: CARD
      END SUBROUTINE BD_FREQ1

   END INTERFACE

   END MODULE BD_FREQ1_Interface
