      MODULE BD_PYRAM_Interface

      INTERFACE

      SUBROUTINE BD_PYRAM ( CARD, LARGE_FLD_INP, NUM_GRD )

      USE PENTIUM_II_KIND, ONLY       :  BYTE, LONG, DOUBLE
      USE IOUNT1, ONLY                :  WRT_ERR, ERR, F06
      USE SCONTR, ONLY                :  BLNK_SUB_NAM, FATAL_ERR, JCARD_LEN, NPYRAM5, NPYRAM14, NELE
      USE TIMDAT, ONLY                :  TSEC
      USE MODEL_STUF, ONLY            :  ETYPE

      IMPLICIT NONE

      CHARACTER(LEN=*), INTENT(INOUT) :: CARD
      CHARACTER(LEN=*), INTENT(IN)    :: LARGE_FLD_INP
      INTEGER(LONG), INTENT(OUT)      :: NUM_GRD

      END SUBROUTINE BD_PYRAM

      END INTERFACE

      END MODULE BD_PYRAM_Interface
