      MODULE BD_PYRAM0_Interface

      INTERFACE

      SUBROUTINE BD_PYRAM0 ( CARD, LARGE_FLD_INP, DELTA_LEDAT )

      USE PENTIUM_II_KIND, ONLY       :  BYTE, LONG, DOUBLE
      USE SCONTR, ONLY                :  BLNK_SUB_NAM, JCARD_LEN, MEDAT_PYRAM5, MEDAT_PYRAM14
      USE TIMDAT, ONLY                :  TSEC

      IMPLICIT NONE

      CHARACTER(LEN=*), INTENT(INOUT) :: CARD
      CHARACTER(LEN=*), INTENT(IN)    :: LARGE_FLD_INP
      INTEGER(LONG), INTENT(OUT)      :: DELTA_LEDAT

      END SUBROUTINE BD_PYRAM0

      END INTERFACE

      END MODULE BD_PYRAM0_Interface
