   MODULE BD_RLOAD1_Interface

   INTERFACE

      SUBROUTINE BD_RLOAD1 ( CARD )
      CHARACTER(LEN=*), INTENT(IN) :: CARD
      END SUBROUTINE BD_RLOAD1

   END INTERFACE

   END MODULE BD_RLOAD1_Interface
