   MODULE BD_TABLED1_Interface

   INTERFACE

      SUBROUTINE BD_TABLED1 ( CARD )
      CHARACTER(LEN=*), INTENT(INOUT) :: CARD
      END SUBROUTINE BD_TABLED1

   END INTERFACE

   END MODULE BD_TABLED1_Interface
