   MODULE BD_TABDMP1_Interface

   INTERFACE

      SUBROUTINE BD_TABDMP1 ( CARD )
      CHARACTER(LEN=*), INTENT(INOUT) :: CARD
      END SUBROUTINE BD_TABDMP1

   END INTERFACE

   END MODULE BD_TABDMP1_Interface
