   MODULE CC_SDAMP_Interface

   INTERFACE

      SUBROUTINE CC_SDAMP ( CARD )
      CHARACTER(LEN=*), INTENT(IN) :: CARD
      END SUBROUTINE CC_SDAMP

   END INTERFACE

   END MODULE CC_SDAMP_Interface
