      MODULE CQUAD4_DKMT20_Interface

      INTERFACE

         SUBROUTINE CQUAD4_DKMT20 ( OPT, INT_ELEM_ID )

         USE PENTIUM_II_KIND, ONLY       :  BYTE, LONG

         IMPLICIT NONE

         CHARACTER(1*BYTE), INTENT(IN)   :: OPT(6)
         INTEGER(LONG), INTENT(IN)       :: INT_ELEM_ID

         END SUBROUTINE CQUAD4_DKMT20

      END INTERFACE

      END MODULE CQUAD4_DKMT20_Interface
