      MODULE CQUADR_MBP1C0_Interface

      INTERFACE

         SUBROUTINE CQUADR_MBP1C0 ( OPT, INT_ELEM_ID )

         USE PENTIUM_II_KIND, ONLY       :  BYTE, LONG

         IMPLICIT NONE

         CHARACTER(1*BYTE), INTENT(IN)   :: OPT(6)
         INTEGER(LONG), INTENT(IN)       :: INT_ELEM_ID

         END SUBROUTINE CQUADR_MBP1C0

      END INTERFACE

      END MODULE CQUADR_MBP1C0_Interface
