      MODULE CQUADR_DKM24AU_Interface

      INTERFACE

         SUBROUTINE CQUADR_DKM24AU ( OPT, INT_ELEM_ID )

         USE PENTIUM_II_KIND, ONLY       :  BYTE, LONG

         IMPLICIT NONE

         CHARACTER(1*BYTE), INTENT(IN)   :: OPT(6)
         INTEGER(LONG), INTENT(IN)       :: INT_ELEM_ID

         END SUBROUTINE CQUADR_DKM24AU

      END INTERFACE

      END MODULE CQUADR_DKM24AU_Interface
