   MODULE CTETRA4S_SMOOTH_ASSEMBLY_Interface

   INTERFACE

      SUBROUTINE CTETRA4S_SMOOTH_ASSEMBLY ( ACTION, LTERM, NTERM )

      USE PENTIUM_II_KIND, ONLY       :  BYTE, LONG
      USE SCONTR, ONLY                :  BLNK_SUB_NAM

      IMPLICIT NONE

      CHARACTER( 5*BYTE), INTENT(IN)  :: ACTION
      INTEGER(LONG), INTENT(IN)       :: LTERM
      INTEGER(LONG), INTENT(INOUT)    :: NTERM

      END SUBROUTINE CTETRA4S_SMOOTH_ASSEMBLY

   END INTERFACE

   END MODULE CTETRA4S_SMOOTH_ASSEMBLY_Interface
