      MODULE CTRIAR_T3FFD_Interface

      INTERFACE

         SUBROUTINE CTRIAR_T3FFD ( OPT, INT_ELEM_ID )

         USE PENTIUM_II_KIND, ONLY       :  BYTE, LONG

         IMPLICIT NONE

         CHARACTER(1*BYTE), INTENT(IN)   :: OPT(6)
         INTEGER(LONG), INTENT(IN)       :: INT_ELEM_ID

         END SUBROUTINE CTRIAR_T3FFD

      END INTERFACE

      END MODULE CTRIAR_T3FFD_Interface
