   MODULE MATMULX_FFF_T_Interface

   INTERFACE

      SUBROUTINE MATMULX_FFF_T ( A, B, NROWA, NCOLA, NCOLB, C )

      USE PENTIUM_II_KIND, ONLY       :  LONG, DOUBLE

      IMPLICIT NONE

      INTEGER(LONG), INTENT(IN)       :: NROWA
      INTEGER(LONG), INTENT(IN)       :: NCOLA
      INTEGER(LONG), INTENT(IN)       :: NCOLB
      REAL(DOUBLE), INTENT(IN)        :: A(NROWA,NCOLA)
      REAL(DOUBLE), INTENT(IN)        :: B(NROWA,NCOLB)
      REAL(DOUBLE), INTENT(OUT)       :: C(NCOLA,NCOLB)

      END SUBROUTINE MATMULX_FFF_T

   END INTERFACE

   END MODULE MATMULX_FFF_T_Interface
