      MODULE PYRAM_Interface

      INTERFACE

      SUBROUTINE PYRAM ( OPT, INT_ELEM_ID, RED_INT_SHEAR, WRITE_WARN )

      USE PENTIUM_II_KIND, ONLY       :  BYTE, LONG, DOUBLE
      USE SCONTR, ONLY                :  BLNK_SUB_NAM

      CHARACTER( 1*BYTE), INTENT(IN)  :: RED_INT_SHEAR
      CHARACTER( 1*BYTE), INTENT(IN)  :: OPT(6)
      CHARACTER(LEN=*), INTENT(IN)    :: WRITE_WARN
      INTEGER(LONG), INTENT(IN)       :: INT_ELEM_ID

      END SUBROUTINE PYRAM

      END INTERFACE

      END MODULE PYRAM_Interface
