      MODULE QUADRATIC_SURFACE_PRESSURE_Interface
      IMPLICIT NONE
      INTERFACE
         SUBROUTINE QUADRATIC_SURFACE_PRESSURE(INT_ELEM_ID,NN,XYZ,CORR,HIGH_ORDER)
         USE PENTIUM_II_KIND, ONLY: LONG,DOUBLE
         INTEGER(LONG),INTENT(IN) :: INT_ELEM_ID,NN
         LOGICAL,INTENT(IN),OPTIONAL :: HIGH_ORDER
      REAL(DOUBLE),INTENT(IN) :: XYZ(NN,3),CORR(8)
         END SUBROUTINE
      END INTERFACE
      END MODULE
