      MODULE QUADRATIC_SURFACE_MASS_Interface
      IMPLICIT NONE
      INTERFACE
         SUBROUTINE QUADRATIC_SURFACE_MASS(NN,XYZ,CORR)
         USE PENTIUM_II_KIND, ONLY: LONG,DOUBLE
         INTEGER(LONG),INTENT(IN) :: NN
         REAL(DOUBLE),INTENT(IN) :: XYZ(NN,3),CORR(8)
         END SUBROUTINE
      END INTERFACE
      END MODULE
