   MODULE READ_L5A_UG_FOR_SUBCASE_Interface

   INTERFACE

      SUBROUTINE READ_L5A_UG_FOR_SUBCASE ( ISUB, IERROR )

      USE PENTIUM_II_KIND, ONLY       :  BYTE, LONG, DOUBLE
      USE IOUNT1, ONLY                :  ERR, F06, L5A, LINK5A, L5A_MSG
      USE SCONTR, ONLY                :  BLNK_SUB_NAM, FATAL_ERR, NDOFG
      USE COL_VECS, ONLY              :  UG_COL

      IMPLICIT NONE

      INTEGER(LONG), INTENT(IN)       :: ISUB
      INTEGER(LONG), INTENT(INOUT)    :: IERROR

      END SUBROUTINE READ_L5A_UG_FOR_SUBCASE

   END INTERFACE

   END MODULE READ_L5A_UG_FOR_SUBCASE_Interface
