   MODULE REBUILD_KLLD_FROM_KGGD_Interface

   INTERFACE

      SUBROUTINE REBUILD_KLLD_FROM_KGGD

      END SUBROUTINE REBUILD_KLLD_FROM_KGGD

   END INTERFACE

   END MODULE REBUILD_KLLD_FROM_KGGD_Interface
