   MODULE WRITE_MATRIX_MARKET_VECTOR_Interface

   INTERFACE

      SUBROUTINE WRITE_MATRIX_MARKET_VECTOR ( VEC_NAME, NUM, VEC, ISUB )

      USE PENTIUM_II_KIND, ONLY       :  BYTE, LONG, DOUBLE

      IMPLICIT NONE

      CHARACTER(LEN=*), INTENT(IN)    :: VEC_NAME
      INTEGER(LONG), INTENT(IN)       :: NUM
      INTEGER(LONG), INTENT(IN)       :: ISUB
      REAL(DOUBLE), INTENT(IN)        :: VEC(NUM)

      END SUBROUTINE WRITE_MATRIX_MARKET_VECTOR

   END INTERFACE

   END MODULE WRITE_MATRIX_MARKET_VECTOR_Interface
