   MODULE WRITE_MATRIX_MARKET_SPARSE_Interface

   INTERFACE

      SUBROUTINE WRITE_MATRIX_MARKET_SPARSE ( MAT_NAME, NROWS, NCOLS, SYM, NTERM_MAT, I_MAT, J_MAT, MAT )

      USE PENTIUM_II_KIND, ONLY       :  BYTE, LONG, DOUBLE

      IMPLICIT NONE

      CHARACTER(LEN=*), INTENT(IN)    :: MAT_NAME
      CHARACTER(1*BYTE), INTENT(IN)   :: SYM
      INTEGER(LONG), INTENT(IN)       :: NROWS
      INTEGER(LONG), INTENT(IN)       :: NCOLS
      INTEGER(LONG), INTENT(IN)       :: NTERM_MAT
      INTEGER(LONG), INTENT(IN)       :: I_MAT(NROWS+1)
      INTEGER(LONG), INTENT(IN)       :: J_MAT(NTERM_MAT)
      REAL(DOUBLE), INTENT(IN)        :: MAT(NTERM_MAT)

      END SUBROUTINE WRITE_MATRIX_MARKET_SPARSE

   END INTERFACE

   END MODULE WRITE_MATRIX_MARKET_SPARSE_Interface
